apiVersion: skaffold/v4beta6
kind: Config
metadata:
  name: connectivity-wizard
build:
  artifacts:
    - image: connectivity-wizard
      hooks:
        before:
        - command: ["make", "build-frontend"]
      # TODO: this does not work
      # TODO: move to Dockerfile
      sync:
        manual:
          - src: "kodata/**/*"
            dest: "/ko-app/"
      ko:
        fromImage: busybox # default: gcr.io/distroless/static:nonroot
manifests:
  rawYaml:
    - k8s/web.yaml
